### ISSUE TITLE
How to use listDirectoryContent in last version?

### ISSUE THREAD

**Issue by bubnenkoff** [salim-lachdhaf/dartFTP#16]
Old one had args like: 
```
ftpConnect!.listDirectoryContent(cmd: DIR_LIST_COMMAND.LIST)
```

new one have mention about `cmd` but do not accept args:
```
  /// Returns the content of the current directory
  /// [cmd] refer to the used command for the server, there is servers working
  /// with MLSD and other with LIST
  Future<List<FTPEntry>> listDirectoryContent() {
    return FTPDirectory(_socket).directoryContent();
  }
 ```
 And on new I am getting an error:
 ```
 FTPConnectException: Connection refused.  (Response: 500 Unknown command.)
 ```

**Comment by danielns1982** [comment]
Same problem here

**Comment by Wishmater** [comment]
Same issue here. I'm ussing directoryContentNames(), which in previous versions did
```
    var list = await listDirectoryContent(
      cmd: DIR_LIST_COMMAND.NLST,
      supportIPV6: supportIPV6,
    );
```
In the latest version, it defaults to MLSD, which in my specific case crashes with
`FTPConnectException: Connection refused.  (Response: 500 Unknown command.)`
And even if it worked, it will request all file details, not only names, which is unnecessary.

**Comment by Wishmater** [comment]
>  ```
> FTPConnect ftpConnect = FTPConnect('<your domain>');
>     await ftpConnect.connect();
>     ftpConnect.listCommand = ListCommand.LIST;
>     return ftpConnect.listDirectoryContent();
> ```

Tried that and it didn't work for me. Still got the same error. For now, I just rolled back version until this is fixed...

**Comment by salim-lachdhaf** [comment]
> I had similar problem, dissecting the new version source it appears that you have to set the command separately, something like this:-
> 
> ```
> FTPConnect ftpConnect = FTPConnect('<your domain>');
>    await ftpConnect.connect();
>    ftpConnect.listCommand = ListCommand.LIST;
>    return ftpConnect.listDirectoryContent();
> ```

this is how it should be.
If it didn't work with LIST try other one, it depends on your server.

**Comment by wengxianxun** [comment]
> 我遇到了类似的问题，剖析新版本源似乎您必须单独设置命令，如下所示：-
> 
> ```
> FTPConnect ftpConnect = FTPConnect('<your domain>');
>    await ftpConnect.connect();
>    ftpConnect.listCommand = ListCommand.LIST;
>    return ftpConnect.listDirectoryContent();
> ```

good
