### ISSUE TITLE
'Error: FTPConnectException: Could not connect to <ipaddress> (21) (Response: Unsupported operation: RawSocket constructor)

### ISSUE THREAD

**Issue by dibsal85** [salim-lachdhaf/dartFTP#24]
i'm on flutter web using 'https://pub.dev/packages/universal_io' instead of 'dart.io'.. is that the problem?

**Comment by MalikSamiAwan** [comment]
@salim-lachdhaf Hi, were you able to find a workaround to connect to ftp from flutter web and if yes can you please share the way i have the same use case. Thankyou
