### ISSUE TITLE
Could not to Upload any Future<Uint8List> 

### ISSUE THREAD

**Issue by berkayhh** [salim-lachdhaf/dartFTP#3]
I would update a Signature Controller with this pub,
But it's not accepting Future<Uint8List> , that must be a String , i think only the Asset files.
Can u explain any way to upload an Future<Uint8List> Data to my Hosting ? 
I can only export to ,
Svg , Raw , PngByte, 
https://pub.dev/packages/signature
Thx for ur Solution.
Regards

**Comment by salim-lachdhaf** [comment]
i will add the possibility to upload `<Uint8List>` in the next versions.
for now , the best solution for you is to convert your `Uint8List` to a File (`File.fromRawPath(Uint8List uint8List)`) and upload it .
