### ISSUE TITLE
Accented letters

### ISSUE THREAD

**Issue by Jackyto** [salim-lachdhaf/dartFTP#7]
Hi,

I work with french accented letters in the filenames but when I use listDirectoryContent(), I have some encoding problems knowing that those files are correctly named on the remote server

IE : 

"I/flutter (23193): AccusÃ© de rÃ©ception.pdf" instead of "Accusé de réception.pdf"

Is there a missing parameter or something I omitted to have properly formatted filenames ?

Thanks in advance

Regards,
Pierre

**Comment by salim-lachdhaf** [comment]
did you tried to change the transfer type ?

**Comment by Jackyto** [comment]
setTransferType() is in the documentation but my IDE cannot find it, is there another way ?

**Comment by salim-lachdhaf** [comment]
```
final FTPConnect _ftpConnect = new FTPConnect("ccccccc", user: "ccccc", pass: "ccccc");
await _ftpConnect .setTransferType(TransferType.binary);
 //await _ftpConnectNoLog.setTransferType(TransferType.ascii);
```

**Comment by Jackyto** [comment]
![cap](https://user-images.githubusercontent.com/2776776/220975219-4e777047-cedf-46e1-843c-3e600d77a366.png)

I cannot use `setTransferType()`

**Comment by salim-lachdhaf** [comment]
make sure that you are using the last version.
