### ISSUE TITLE
 '_socket@1665506163' has not been initialized.

### ISSUE THREAD

**Issue by GiulioWecove** [salim-lachdhaf/dartFTP#8]
I have this error when trying to use this package at version 2.0.2:

[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field '_socket@1665506163' has not been initialized.

And it point to this file and line: ftp_socket.dart:195

I'm testing it on an iPhone S.

**Comment by salim-lachdhaf** [comment]
could you past a simple reproductible code ?

**Comment by salim-lachdhaf** [comment]
but you did not test on `isConnected`  !
`bool isConnected = await ftpConnect.connect();` crashes `await ftpConnect.disconnect();` will crash either because socket is not initialized or not connected.

Make sure that await `ftpConnect.connect();` returns `true.`
