### ISSUE TITLE
FTPEntry not a type

### ISSUE THREAD

**Issue by nicolasvahidzein** [salim-lachdhaf/dartFTP#9]
Hello,

I am getting a weird error in my project using your package for the first time:

The name 'FTPEntry' isn't a type, so it can't be used as a type argument.
Try correcting the name to an existing type, or defining a type named 'FTPEntry'.dart[non_type_as_type_argument](https://dart.dev/diagnostics/non_type_as_type_argument)

**Comment by bubnenkoff** [comment]
Same issue. 
Dart 3.0

**Comment by OkilSaber** [comment]
Hello the solution to this is to import the source code of the class like this:
``import 'package:ftpconnect/src/ftp_entry.dart';``

**Comment by salim-lachdhaf** [comment]
issue fixed in 2.0.6
